services:
  official:
    container_name: bench_official
    build:
      context: .
      dockerfile: Dockerfile.official
    volumes:
      - ./config.json:/config.json
      - ./results:/results
    environment:
      IMAGE_NAME: official
  pyenvfullopt:
    container_name: bench_pyenvfullopt
    build:
      context: .
      dockerfile: Dockerfile.pyenv.fullopt
      args:
        PYTHON_VERSION: "3.12.3"
    volumes:
      - ./config.json:/config.json
      - ./results:/results
    environment:
      IMAGE_NAME: pyenvfullopt
  pyenvmiopt:
    container_name: bench_pyenvmiopt
    build:
      context: .
      dockerfile: Dockerfile.pyenv.miopt
      args:
        PYTHON_VERSION: "3.12.3"
    volumes:
      - ./config.json:/config.json
      - ./results:/results
    environment:
      IMAGE_NAME: pyenvmiopt
  pyenvbasic:
    container_name: bench_pyenv_basic
    build:
      context: .
      dockerfile: Dockerfile.pyenv.basic
      args:
        PYTHON_VERSION: "3.12.3"
    volumes:
      - ./config.json:/config.json
      - ./results:/results
    environment:
      IMAGE_NAME: pyenvbasic
  uv:
    container_name: bench_uv
    build:
      context: .
      dockerfile: Dockerfile.uv
      args:
        PYTHON_VERSION: "3.12.3"
    volumes:
      - ./config.json:/config.json
      - ./results:/results
    environment:
      IMAGE_NAME: uv
